### ISSUE TITLE
Read/write timeout due to Mcb_IntfIRQEvent 

### ISSUE THREAD

**Issue by thebolt** [ingeniamc/mcblib#3]
I initially implemented communications as specified in the documentation by overriding methods listed in mcb_usr.h (Mcb_IntfReadIRQ, Mcb_IntfIsReady, Mcb_GetMillis, Mcb_IntfSPITransfer) using polling and busy-waiting for the IRQ line before performing SPI communication.

This resulted in all read/writes (blocking mode) ending with timeout.

After contact with Ingeniamc support it was worked out that it is _required_ to call Mcb_IntfIRQEvent either from ISR handler or once IRQ line goes high after SPI transfer.

Recommend that documentation is updated.

**Comment by ghost** [comment]
Hi!

We have added this page into the documentation to try to clarify how to implement and use everything inside the mcb_usr.h file

https://github.com/ingeniamc/mcblib/wiki/HAL-adaptation

Tell us if this helps or if there is anything missing for your development.

Thank you!

**Comment by thebolt** [comment]
Thanks, that helps. I have solved it, but for others it would answers the questions I had.
